# Generated by Django 3.1.13 on 2021-08-19 17:23

from django.db import migrations
import mapbox_location_field.spatial.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=mapbox_location_field.spatial.models.SpatialLocationField(blank=True, map_attrs={}, null=True, srid=4326),
        ),
    ]
