# Generated by Django 3.1.13 on 2021-08-19 09:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_austinhex'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_report_id', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField()),
                ('issue_reported', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('status_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
