# Generated by Django 3.1.13 on 2021-08-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20210819_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficincident',
            name='issue_reported',
            field=models.CharField(blank=True, choices=[('ZV', 'zSTALLED VEHICLE'), ('TH', 'Traffic Hazard'), ('CU', 'Crash Urgent'), ('CS', 'Crash Service'), ('CO', 'COLLISION'), ('TD', 'TRFC HAZD/ DEBRIS'), ('TI', 'Traffic Impediment'), ('CW', 'COLLISION WITH INJURY'), ('LL', 'LOOSE LIVESTOCK'), ('CL', 'COLLISN/ LVNG SCN'), ('SV', 'Stalled Vehicle'), ('CP', 'COLLISION/PRIVATE PROPERTY'), ('VH', 'VEHICLE FIRE'), ('BD', 'BLOCKED DRIV/ HWY'), ('BA', 'BOAT ACCIDENT'), ('TF', 'TRAFFIC FATALITY'), ('AP', 'AUTO/ PED'), ('IR', 'ICY ROADWAY'), ('FA', 'FLEET ACC/ INJURY'), ('NH', 'N / HZRD TRFC VIOL')], max_length=2, null=True),
        ),
    ]
