# Generated by Django 3.1.13 on 2021-08-19 13:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20210819_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='austinhex',
            name='hex',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
