# Generated by Django 3.1.13 on 2021-08-19 14:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20210819_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('density', models.DecimalField(decimal_places=4, max_digits=8)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
